# Generated by Django 4.2.16 on 2024-12-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_image',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_title',
        ),
    ]
