# Generated by Django 4.2.16 on 2024-12-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
        ('watchlist', '0002_alter_watchlist_unique_together_watchlist_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='movies.movie'),
            preserve_default=False,
        ),
    ]
