# Generated by Django 4.2.16 on 2024-12-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
