# Generated by Django 4.2.16 on 2024-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_name_remove_post_intro_comment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('action', 'Action'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('biopic', 'Biopic'), ('documentary', 'Documentary'), ('family', 'Family')], max_length=30)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
