# Generated by Django 4.2.16 on 2024-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
