# Generated by Django 4.2.16 on 2024-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_poster_url_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
