# Generated by Django 4.2.16 on 2024-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
